dist: bionic
language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.npm
    - .spago
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - node
install:
  - npm install -g purescript spago
script:
  - spago run
